name: Build and Test 

on:
  push:
    branches:
    - master
    - staging
    - development
jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v2

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: anjardanis/stealth-test
          registry: docker.io
          tags: ${{ github.sha }},latest
          buildArgs: GIT_VERSION:1.0, GIT_COMMIT:${{ github.sha }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


  running_test:
    runs-on: ubuntu-latest
    needs: [build_docker]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Test
        run: |
          docker pull anjardanis/stealth-test:latest
          docker run anjardanis/stealth-test:latest sh -c "npm test"
